@url = http://localhost:5000
@userId = af2210ff-011a-4405-a656-0ff6026152c4

###
GET {{url}}

###
GET {{url}}/api/users

###
GET {{url}}/api/users/{{userId}}

###
POST {{url}}/api/users
Content-Type: application/json

{
  "email": "user1@fastpay.io",
  "fullName": "John Doe",
  "password": "secret1234",
  "nationality": "PL"
}


###
PUT {{url}}/api/users/{{userId}}/verify


###
GET {{url}}/users?name=user1&age=20

###
GET {{url}}/users/{{userId}}

###
POST {{url}}/users
Content-Type: application/json

{
  "email": "user1@fastpay.io",
  "fullName": "John Doe",
  "password": "secret1234",
  "nationality": "PL"
}

###
PUT {{url}}/users/{{userId}}/verify
