@url = http://localhost:5000
@userId = 7632c04b-d09f-42b8-a0e9-1a33c768a22c

###
GET {{url}}

###
GET {{url}}/api/users

###
GET {{url}}/api/users/{{userId}}

###
POST {{url}}/api/users
Content-Type: application/json

{
  "email": "user1@fastpay.io",
  "fullName": "John Doe",
  "password": "secret1234",
  "nationality": "PL"
}


###
PUT {{url}}/api/users/{{userId}}