@url = http://localhost:5000

###
GET {{url}}

# ----------------
#   Endpoints
# ----------------

# Users

###
@userId = cd97a973-a820-48d3-99bd-5323d9bd4171

###
GET {{url}}/api/users

###
GET {{url}}/api/users/{{userId}}

###
POST {{url}}/api/users
Content-Type: application/json

{
  "email": "user1@fastpay.io",
  "fullName": "John Doe",
  "password": "secret1234",
  "nationality": "PL"
}

###
PUT {{url}}/api/users/{{userId}}/verify


# ----------------
#   Controllers
# ----------------

# Users

###
GET {{url}}/users

###
GET {{url}}/users/{{userId}}

###
POST {{url}}/users
Content-Type: application/json

{
  "email": "user1@fastpay.io",
  "fullName": "John Doe",
  "password": "secret1234",
  "nationality": "PL"
}

###
PUT {{url}}/users/{{userId}}/verify

# Wallets

###
@fromWalletId = f30881c8-8544-4516-a92a-6cf0993800b7
@toWalletId = 00000000-0000-0000-0000-000000000000

###
GET {{url}}/wallets

###
GET {{url}}/wallets/{{fromWalletId}}

###
POST {{url}}/wallets
Content-Type: application/json

{
  "userId": "{{userId}}",
  "currency": "EUR"
}

###
DELETE {{url}}/wallets/{{fromWalletId}}